[package]
name = "bad_idea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
nalgebra = "0.30.1"
rayon = "1.5.1"

[features]
